-- Create the licenses table in your Supabase project
create table licenses (
  id bigint generated by default as identity primary key,
  key text unique not null,
  status text check (status in ('active', 'inactive', 'suspended')) default 'active',
  domain text,
  type text default 'standard',
  expiry_date timestamptz,
  activated_at timestamptz,
  created_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
alter table licenses enable row level security;

-- Policy to allow Service Role (server) to read/write all
create policy "Enable all access for service role" on licenses
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
